### ISSUE TITLE
Cant setup Multibranch pipeline with BPPR plugin. 

### ISSUE THREAD

**Issue by mixMugz** [jenkinsci/bitbucket-push-and-pull-request-plugin#78]
Created multibranch pipeline.
Instaled latest version addon.
Created webhook.

Jobs not trigering with push events.

Do you have any extended manual to setup plugin with multibranch pipeline?

**Comment by eiriarte-mendez** [comment]
hi @mixMugz 

here is a snippet working for me:
```groovy
pipeline {

  agent any
  
  triggers {
    bitBucketTrigger([
      [
        // $class: 'BitBucketPPRPullRequestTriggerFilter', // use this class for BitBucket Cloud instead.
        $class: 'BitBucketPPRPullRequestServerTriggerFilter',
        triggers: [
          [
            $class: 'BitBucketPPRPullRequestServerTriggerFilter',
            actionFilter: [
              $class: 'BitBucketPPRPullRequestCreatedActionFilter',
            ]
          ],
          [
            $class: 'BitBucketPPRPullRequestServerTriggerFilter',
            actionFilter: [
              $class: 'BitBucketPPRPullRequestApprovedActionFilter',
            ]
          ],
          [
            $class: 'BitBucketPPRPullRequestServerTriggerFilter',
            actionFilter: [
              $class: 'BitBucketPPRPullRequestUpdatedActionFilter',
            ]
          ],
          [
            $class: 'BitBucketPPRPullRequestServerTriggerFilter',
            actionFilter: [
              $class: 'BitBucketPPRPullRequestMergedActionFilter',
            ]
          ],
          [
            $class: 'BitBucketPPRRepositoryTriggerFilter',
            actionFilter: [
              $class: 'BitBucketPPRRepositoryPushActionFilter',
              triggerAlsoIfNothingChanged: true,
              triggerAlsoIfTagPush: false,
              allowedBranches: ""
            ]
          ]
        ]
      ]
    ])
  }

  stages {
    stage('Stage 1') {
      steps {
        echo 'Building...'

        echo 'Env vars for cloud pull request...'
        echo "BITBUCKET_SOURCE_BRANCH ${env.BITBUCKET_SOURCE_BRANCH}"
        echo "BITBUCKET_TARGET_BRANCH ${env.BITBUCKET_TARGET_BRANCH}"
        echo "BITBUCKET_PULL_REQUEST_LINK ${env.BITBUCKET_PULL_REQUEST_LINK}"
        echo "BITBUCKET_PULL_REQUEST_ID ${env.BITBUCKET_PULL_REQUEST_ID}"
        echo "BITBUCKET_PAYLOAD ${env.BITBUCKET_PAYLOAD}"

        echo 'Env vars for cloud push...'
        echo "REPOSITORY_LINK ${env.REPOSITORY_LINK}"
        echo "BITBUCKET_SOURCE_BRANCH ${env.BITBUCKET_SOURCE_BRANCH}"
        echo "BITBUCKET_REPOSITORY_URL ${env.BITBUCKET_REPOSITORY_URL}"
        echo "BITBUCKET_PUSH_REPOSITORY_UUID ${env.BITBUCKET_PUSH_REPOSITORY_UUID}"
        echo "BITBUCKET_PAYLOAD ${env.BITBUCKET_PAYLOAD}"

        echo 'Env vars for server push...'
        echo "REPOSITORY_LINK ${env.REPOSITORY_LINK}"
        echo "BITBUCKET_SOURCE_BRANCH ${env.BITBUCKET_SOURCE_BRANCH}"
        echo "BITBUCKET_REPOSITORY_URL ${env.BITBUCKET_REPOSITORY_URL}"
        echo "BITBUCKET_PUSH_REPOSITORY_UUID ${env.BITBUCKET_PUSH_REPOSITORY_UUID}"
        echo "BITBUCKET_PAYLOAD ${env.BITBUCKET_PAYLOAD}"
      }
    }
  }
}
```

however I was forced to set a cron/interval-trigger in the multibranch root job, otherwise branches do not start automatically... @macghriogair is this intendend?

**Comment by tomasz-lagodzinski-ynd** [comment]
I seem to have the same issue, 
 - Multibranch Pipeline, 
 - latest jenkins and plugin 
 - BB Cloud

Tested multiple configurations. Everything is fine for branch builds. PR builds seem to be Skipped.

I've kinda tracked it down to the following discrepancy.

Job type for Multibranch Project is returned as: org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject

wheras the code here:
https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/blob/c91f34c76eaa172d77b3aa4a9f45405c6918bd80/src/main/java/io/jenkins/plugins/bitbucketpushandpullrequest/BitBucketPPRJobProbe.java#L143

is checking for if it's an instance of MultiBranchProject. Which is actually the parent of WorkflowMultiBranchProject

scripted pipeline with the following config:
```
pipelineTriggers([
    bitBucketTrigger([
      [
        $class: 'BitBucketPPRRepositoryTriggerFilter',
        actionFilter: [
          $class: 'BitBucketPPRRepositoryPushActionFilter',
          allowedBranches: 'develop',
          triggerAlsoIfNothingChanged: false,
          triggerAlsoIfTagPush: false
        ]
      ],
      [
        $class: 'BitBucketPPRPullRequestTriggerFilter',
        actionFilter: [
          $class: 'BitBucketPPRPullRequestUpdatedActionFilter',
          allowedBranches: ''
        ]
      ],
      [
        $class: 'BitBucketPPRPullRequestTriggerFilter',
        actionFilter: [
          $class: 'BitBucketPPRPullRequestCreatedActionFilter',
          allowedBranches: ''
        ]
      ]
    ])
  ])
```

Log from the plugin, target branch name removed for being quite sensitive:
```
Job is of type: org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject
Bitbucket event is : push
Job Name : PR-134
sourceBranchName: null 
Skipping for job:PR-134
```

**Comment by emreakcan** [comment]
Hello, any updates on this?

**Comment by B-Lukas** [comment]
I would also like an Update on this

**Comment by Sleepy-GH** [comment]
I think I accidentally filed a bug for the same issue, but I may have found the cause. See last comment in: https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/issues/123

**Comment by MikeKroell** [comment]
I am also having an issue trying to use this plugin for multi-branch.

**Comment by cdelmonte-zg** [comment]
Solved with release 2.5.1

**Comment by shaktiug** [comment]
I am still getting it null
echo env.BITBUCKET_TARGET_BRANCH
echo env.BRANCH_NAME
echo env.BITBUCKET_SOURCE_BRANCH

00-00-0000 00:00:04.269  null
00-00-0000 00:00:04.282  [Pipeline] echo
00-00-0000 00:00:04.286  feature/sprint-1
00-00-0000 00:00:04.309  [Pipeline] echo
00-00-0000 00:00:04.313  null
